export const UserRegistrationType = {
  USER_REGISTER_REQUEST: "USER_REGISTER_REQUEST",
  USER_REGISTER_SUCCESS: "USER_REGISTER_SUCCESS",
  USER_REGISTER_FAIL: "USER_REGISTER_FAIL",
};

export const UserLoginType = {
  USER_LOGIN_REQUEST: "USER_LOGIN_REQUEST",
  USER_LOGIN_SUCCESS: "USER_LOGIN_SUCCESS",
  USER_LOGIN_FAIL: "USER_LOGIN_FAIL",
};

export const UserVerifyType = {
  USER_VERIFY_REQUEST: "USER_VERIFY_REQUEST",
  USER_VERIFY_SUCCESS: "USER_VERIFY_SUCCESS",
  USER_VERIFY_FAIL: "USER_VERIFY_FAIL",
};
